### ISSUE TITLE
 Paper Queries

### ISSUE THREAD

**Issue by DeepOceanDeep** [PKU-ML/AdvNotRealFeatures#3]
Hey,

I've got a few questions about some points in the paper. When you mention that adversarial examples aren't real features, does that also mean that using FGSM and its optimal perturbations isn't helpful for tasks other than classification?

Also, with non-robust features, starting from noise results in final images that look like noise, but when you feed them into a classifier, they still get classified with high probability. Have you looked into how starting from noise or from an image affects classification confidence?

And what's the difference between generating optimal perturbations with FGSM and creating non-robust features?

Thank you

**Comment by Charles20021201** [comment]
Hi,
Thanks for reading our work! I may answer your questions as follows:

(1) Do you mean "transferable" by "helpful"? As we show experimentally, the adversarial perturbations hardly transfer between paradigms (Generative v.s. discriminative). I believe FGSM is likely to behave similarly to the PGD attack considered in the paper.

(2) Yes. We observed that non-robust datasets construced from noise (denoted as D_noise) exhibited worse performance than those constructed from natural images (denoted as D_natural). For example, using the CIFAR10 dataset, a ResNet-18 trained on D_noise achieves around 30% lower test accuracy than that trained on D_natural.

(3) First of all, I am afraid that FGSM does NOT bring optimal perturbations since there are many stronger adversarial attacks, e.g., PGD and CW attack. FGSM, which is essentially an optimization algorithm, can be used to find non-features.  

If there are more questions, just ask!
Charles

**Comment by DeepOceanDeep** [comment]
Thanks for your thoughts and answers @Charles20021201 
Regarding Question3 I mean, is there any difference between optimal perturbation achieved by attacks like FGM, PGD, CW, etc. and non-robust features?  I feel these are the same concepts under different name.

**Comment by Charles20021201** [comment]
> Thanks for your thoughts and answers @Charles20021201 Regarding Question3 I mean, is there any difference between optimal perturbation achieved by attacks like FGM, PGD, CW, etc. and non-robust features? I feel these are the same concepts under different name.

Hi,
I would say there are still subtle differences between adversarial perturbations and non-robust features. For example, consider using PGD to attack a robustly trained model. Since the robust model mostly relies on robust features, the resulting adversarial perturbations are more like robust features rather than non-robust ones.  But your intuition is mostly correct, given a natural model and some data, adversarial attacks are indeed the most common way to find non-robust features

**Comment by DeepOceanDeep** [comment]
Thanks very very much @Charles20021201 for your insight and helpful answer. Appreciate it!
